# Podfile

use_frameworks!

target "TestExample" do
  # Normal libraries

  abstract_target 'Tests' do
    inherit! :search_paths
    target "TestExampleTests"
    target "TestExampleUITests"

    pod 'Nimble'
    pod 'Quick'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # to whatever swift version you're using
    end
  end
end
